#!/bin/bash
# suspends the computer (saved to memory) and reawakens it at specified regular times
# needs to be invoked manually with sudo because rtcwake and crontab require it

PROGN=${0##*/}
PD=$( dirname $( dirname $(realpath $0)))

while [ "$#" -gt 0 ]; do
  tabs 3
  case "$1" in
    -h|--help) 
	printf "$PROGN %s\n\t%s\n\t%s\n\t%s\n\t%s\n\t%s\n\t\t%s\n" \
	'options: (long versions work too, e.g. -h or --help)' \
    '-r|--repeat: set up crontab for repeated invocations' \
    '-w|--wake: cancel crontab to stay awake' \
    '-a|--advance: to allow computer to wake in time (default 10 s)' \
	  '-s|--start: first waking up after each hour (default 60 s)' \
	  '-g|--gaps: seconds between repetitions (default 300 s)' \
	  '(g > S) and g one of: [1,2,3,4,5,6,10,12,15,20,30]'	
	exit 1;;
    -r|--repeat) R=0; shift 1;;
    -w|--wake) crontab -u root -r; exit 1;;
    -a|--advance) A="$2"; shift 2;;
	  -s|--start) S="$2"; shift 2;;
    -g|--gaps) G="$2"; shift 2;;
    -*|--*) printf "$PROGN: unknown option: $1, try -h\n" 2>&1; exit 2;;
    *) printf "malformed option $1: options must start with - or --, try -h or --help\n" 2>&1; exit 2;;
  esac
done
if [ -z "$A" ]; then A=10; fi
if [ -z "$S" ]; then S=60; fi
if [ -z "$G" ]; then G=300; fi

# set up and start crontab which will suspend one minute after the regular $S+$G time
# and reawaken $A seconds before the next one, using this script (this time without -r)
if [ $R ]; then
  SM=$(( $S/60+1 )) # start in minutes, plus one, to allow one awake minute
  GM=$(( $G/60 )) # gaps in minutes
  printf "TZ=UTC\n$SM-59/$GM * * * * sudo $PD/bin/sleeper -a $A -s $S -g $G >> $PD/data/sleepercronlog\n" | crontab -u root -  
fi
# the rest is executed either manually or by crontab causing suspend
# calculate for how many seconds to suspend (sleep) for, using modulo arithmetic on unix seconds
# start with basic gap increment of $G seconds
# subtract start from unix seconds to get time we would have now if there was no start offset delay
# get (modulo $G)  pure execution time already elapsed
# subtract seconds advance $A
sudo rtcwake -m mem -u -s $(( $G-($(date +%s)-$S)%$G-$A ))
